### ISSUE TITLE
npm run api-docs throws exception

### ISSUE THREAD

**Issue by lordgreg** [ionic-team/ionic-docs#18]
# Issue - all hell broke lose
```
Gregor@skynet /c/Development/ionic-docs (master)
$ npm run api-docs

> @ionic/ionic-docs@0.2.0 preapi-docs C:\Development\ionic-docs
> tsc -p scripts/tsconfig.json


> @ionic/ionic-docs@0.2.0 api-docs C:\Development\ionic-docs
> node scripts/build/scripts

 √ Precheck
 > Generating
   \ API Docs
     → Updating...
   \ CLI Docs
     → Updating...
   \ Native Docs
     → Updating...
   \ Storage Docs
     → Updating...
{ Error: Command failed: git clone https://github.com/ionic-team/ionic-native.git sources/ionic-native
fatal: destination path 'sources/ionic-native' already exists and is not an empty directory.

    at ChildProcess.exithandler (child_process.js:272:12)
 √ Precheck
 > Generating
   / API Docs
     → NPM Installing 4.0.0-alpha.6
   / CLI Docs
     → NPM Installing & Building...
   × Native Docs
     → operable program or batch file.
   √ Storage Docs
{ Error: Command failed: cd sources/ionic-native && ../../node_modules/.bin/typedoc --json dist/docs.json --mode modules src/@ionic-native/plugins/*/index.ts
'..' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:127:13)
    at maybeClose (internal/child_process.js:933:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cd sources/ionic-native && ../../node_modules/.bin/typedoc --json dist/docs.json --mode modules src/@ionic-native/plugins/*/index.ts',
  stdout: '',
  stderr: '\'..\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n',  context: {} }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ionic/ionic-docs@0.2.0 api-docs: `node scripts/build/scripts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ionic/ionic-docs@0.2.0 api-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gregor\AppData\Roaming\npm-cache\_logs\2018-05-23T20_15_38_156Z-debug.log
```

OS Window 10, latest
```
$ node --version && npm --version
v9.6.1
6.0.1
```

So I cannot compile or use the API docs at all since this issue is appearing all the time.

# Where's the catch?

1. not using `npx` command when calling typedoc
2. meanwhile, you will most probably have this issue: https://github.com/zkat/npx/issues/144. Fix it by following the instructions in comment: https://github.com/zkat/npx/issues/144#issuecomment-391031816
3. Try building locally, 
```
$ npx typedoc --json dist/docs.json --mode modules src/@ionic-native/plugins/*/index.ts
ENOENT: no such file or directory, stat 'C:\Development\ionic-docs\src\@ionic-native\plugins\*\index.ts'
```
Oh right, proper folder!
```
Gregor@skynet /c/Development/ionic-docs/sources/ionic-native (v5)
$ npx typedoc --json dist/docs.json --mode modules src/@ionic-native/plugins/*/index.ts
npx: installed 61 in 11.431s

Using TypeScript 2.7.2 from C:\Users\Gregor\AppData\Roaming\npm-cache\_npx\10692\node_modules\typedoc\node_modules\typescript\lib

JSON written to C:\Development\ionic-docs\sources\ionic-native\dist\docs.json
```

This shouldn't be such a failure :(

**Comment by perrygovier** [comment]
The `api-docs` commands are meant not really intended to be used by the public. The content from these page comes directly from the source, so if any changes are necessary, they should come from the source. 

There are two points of failure here, one is that prior to this, your script failed or was cancelled mid-checkout and you have a dirty sources directory. Deleting what's there and allowing the scripts to complete or fail on their own should resolve that issue. The second is that these have not been written in a windows compatible way as they're never meant to run on a windows filesystem. 

Thank you for taking the time to submit this issue. Please remember to be respectful. I'm going to close this since it's not really a priority for us that users working on content updates are able to run the CI scripts in different environments.
