### ISSUE TITLE
API Documentation not Found

### ISSUE THREAD

**Issue by chrislow** [ionic-team/ionic-docs#23]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**

```
http://localhost:3333/docs/api/action-sheet
```

**Current behavior:**

```
Unable to fetch api/action-sheet: Not Found
```

**Expected behavior:**

It should show the component api documentation.

**Steps to reproduce:**

1. ``` $ git clone https://github.com/ionic-team/ionic-docs.git ```
2. ``` $ git submodule update --init ```
3. ``` $ npm install ```
4. ``` $ npm run dev  ```
5. Open http://localhost:3333/docs/api/action-sheet

**Other information:**

 ``` Bash
$ npm -v
6.1.0

$ node -v
v8.11.1
```

**Comment by chrislow** [comment]
running `npm run api-docs` throws following error on windows 10:

```Bash
$ npm run api-docs

> @ionic/ionic-docs@0.2.0 preapi-docs C:\xampp\htdocs\ionic-docs
> tsc -p scripts/tsconfig.json


> @ionic/ionic-docs@0.2.0 api-docs C:\xampp\htdocs\ionic-docs
> node scripts/build/scripts

 √ Precheck
 √ Precheck
 > Generating
   \ API Docs
     → Updating...
   \ CLI Docs
     → NPM Installing & Building...
   × Native Docs
     →     at Object.Module._extensions..js (module.js:663:10)
   √ Storage Docs
{ Error: Command failed: cd sources\ionic-native && ..\..\node_modules\.bin\typedoc --json dist\docs.json --mode modules src\@ionic-native\plugins\*\index.ts
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat 'C:\xampp\htdocs\ionic-docs\sources\ionic-native\src\@ionic-native\plugins\*\index.ts'
    at Object.fs.statSync (fs.js:948:11)
    at C:\xampp\htdocs\ionic-docs\node_modules\typedoc\dist\lib\application.js:145:20
    at Array.forEach (<anonymous>)
    at CliApplication.Application.expandInputFiles (C:\xampp\htdocs\ionic-docs\node_modules\typedoc\dist\lib\application.js:143:20)
    at CliApplication.bootstrap (C:\xampp\htdocs\ionic-docs\node_modules\typedoc\dist\lib\cli.js:58:28)
    at CliApplication.Application [as constructor] (C:\xampp\htdocs\ionic-docs\node_modules\typedoc\dist\lib\application.js:41:15)
    at new CliApplication (C:\xampp\htdocs\ionic-docs\node_modules\typedoc\dist\lib\cli.js:35:42)
    at Object.<anonymous> (C:\xampp\htdocs\ionic-docs\node_modules\typedoc\bin\typedoc:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cd sources\\ionic-native && ..\\..\\node_modules\\.bin\\typedoc --json dist\\docs.json --mode modules src\\@ionic-native\\plugins\\*\\index.ts',  stdout: '',
  stderr: 'fs.js:948\r\n  binding.stat(pathModule._makeLong(path));\r\n          ^\r\n\r\nError: ENOENT: no such file or directory, stat \'C:\\xampp\\htdocs\\ionic-docs\\sources\\ionic-native\\src\\@ionic-native\\plugins\\*\\index.ts\'\r\n    at Object.fs.statSync (fs.js:948:11)\r\n    at C:\\xampp\\htdocs\\ionic-docs\\node_modules\\typedoc\\dist\\lib\\application.js:145:20\r\n    at Array.forEach (<anonymous>)\r\n    at CliApplication.Application.expandInputFiles (C:\\xampp\\htdocs\\ionic-docs\\node_modules\\typedoc\\dist\\lib\\application.js:143:20)\r\n    at CliApplication.bootstrap (C:\\xampp\\htdocs\\ionic-docs\\node_modules\\typedoc\\dist\\lib\\cli.js:58:28)\r\n    at CliApplication.Application [as constructor] (C:\\xampp\\htdocs\\ionic-docs\\node_modules\\typedoc\\dist\\lib\\application.js:41:15)\r\n    at new CliApplication (C:\\xampp\\htdocs\\ionic-docs\\node_modules\\typedoc\\dist\\lib\\cli.js:35:42)\r\n    at Object.<anonymous> (C:\\xampp\\htdocs\\ionic-docs\\node_modules\\typedoc\\bin\\typedoc:4:1)\r\n    at Module._compile (module.js:652:30)\r\n    at Object.Module._extensions..js (module.js:663:10)\r\n',  context: {} }npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! @ionic/ionic-docs@0.2.0 api-docs: `node scripts/build/scripts`npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ionic/ionic-docs@0.2.0 api-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Christian\AppData\Roaming\npm-cache\_logs\2018-06-11T17_35_03_578Z-debug.log
```

**Comment by perrygovier** [comment]
These scripts aren't really meant for public consumption, and so I decided to opt for a node v9+ dependency and didn't worry too much about Windows compatibility. That said, they should work on Windows, it's just a low priority at this point.

**Comment by kael** [comment]
@perrygovier : Can you describe in the README the correct and simple way to generate the documentation ?

The doc about the doc is a bit laconic, though.
