### ISSUE TITLE
v4 native docs: admob-free setup instructions incorrect

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#278]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/native/admob-free

**Issue:**
Had a look around to find the actual file to edit in the repo but couldn't figure out its location and edit on GitHub link doesn't work on docs site.

Url above has installation instructions but they don't work.

Executing `ionic cordova plugin add cordova-plugin-admob-free` gives an error:

```
> cordova plugin add cordova-plugin-admob-free --save
Installing "cordova-plugin-admob-free" for android
Failed to install 'cordova-plugin-admob-free': Error: Variable(s) missing: ADMOB_APP_ID
    at Object.mergeVariables (C:\Users\rtpha\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\variable-merge.js:58:15)
    at C:\Users\rtpha\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:315:44
    at _fulfilled (C:\Users\rtpha\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:854:54)
    at C:\Users\rtpha\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\rtpha\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:13)
    at C:\Users\rtpha\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\rtpha\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\rtpha\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
Variable(s) missing: ADMOB_APP_ID
    at process._tickCallback (internal/process/next_tick.js:61:11)
[ERROR] An error occurred while running subprocess cordova.
```

**Solution:**
Should be run with the `variable` parameter instead:

`ionic cordova plugin add cordova-plugin-admob-free --variable ADMOB_APP_ID=ca-app-pub-xxxx-xxxxx`

**Comment by camwiegert** [comment]
Addressing this as part of #328
